artifactDescription: "DIH Domain"
annotationLibrary: "none"
artifactId: "domain"
dateLibrary: "java8"
groupId: "dk.rdpl.dih"
modelPackage: "dk.rdpl.dih.domain.model"
scmConnection: ""
serializationLibrary: "jackson"
performBeanValidation: "true"
useBeanValidation: "true"
scmDeveloperConnection: ""
scmUrl: ""
